### model
model_name_or_path: /home/hidelord/text-generation-webui-snapshot-2024-04-14/models/Incomplete_Class

### method
stage: kto
pref_beta: 0.05
do_train: true
finetuning_type: lora

### lora
lora_rank: 320
lora_alpha: 550
lora_dropout: 0.05
lora_target: all

### optim
flash_attn: fa2
enable_liger_kernel: true
optim: lion_8bit

### ddp
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: incomplete_dataset_kto
dataset_dir: data
template: phi
seed: 66
cutoff_len: 4000
preprocessing_num_workers: 16
use_fast_tokenizer: true

### output
output_dir: /home/hidelord/text-generation-webui-snapshot-2024-04-14/models/Incomplete_Class_kto
logging_steps: 5
save_steps: 100000
overwrite_output_dir: true
run_name: Incomplete_Class_kto

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
learning_rate: 0.000015
num_train_epochs: 1.0
lr_scheduler_type: polynomial
bf16: true
max_grad_norm: 1.0
warmup_steps: 25
weight_decay: 0.01

### eval
val_size: 0.05
per_device_eval_batch_size: 4
evaluation_strategy: steps
eval_steps: 40
save_total_limit: 1
save_only_model: true
