### model
model_name_or_path: /home/hidelord/text-generation-webui-snapshot-2024-04-14/models/Qwen2.5-1.5B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
flash_attn: fa2
enable_liger_kernel: true
optim: adamw_8bit

### ddp
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z0_config.json

### dataset
dataset: lang_dataset
dataset_dir: data
template: qwen
data_seed: 66
seed: 66
cutoff_len: 2000
preprocessing_num_workers: 16
use_fast_tokenizer: true

### output
output_dir: saves/full/Lang_Class_0.1
logging_steps: 5
save_steps: 75
overwrite_output_dir: true
run_name: Lang_Class_0.1

### train
per_device_train_batch_size: 10
gradient_accumulation_steps: 1
learning_rate: 0.00001
num_train_epochs: 1.0
lr_scheduler_type: polynomial
bf16: true
max_grad_norm: 1.0
warmup_steps: 10
weight_decay: 0.01

### eval
val_size: 0.05
per_device_eval_batch_size: 2
evaluation_strategy: steps
eval_steps: 75
save_total_limit: 1
save_only_model: true
