### model
model_name_or_path: /home/hidelord/text-generation-webui-snapshot-2024-04-14/models/phi-3-mini-4k-instruct

### method
stage: sft
do_train: true
finetuning_type: lora
low_cpu_mem_usage: true
flash_attn: fa2
enable_liger_kernel: true
optim: lion_8bit

### lora
lora_rank: 220
lora_alpha: 440
lora_dropout: 0.05
lora_target: all

### ddp
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z0_config.json

### dataset
dataset: moral_dataset
dataset_dir: data
template: phi
data_seed: 66
seed: 66
cutoff_len: 2500
preprocessing_num_workers: 16
use_fast_tokenizer: true

### output
output_dir: /home/hidelord/text-generation-webui-snapshot-2024-04-14/models/Moral_Class_0.1
logging_steps: 5
save_steps: 20000
overwrite_output_dir: true
run_name: Moral_Class_0.1

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 0.000075
num_train_epochs: 1.0
lr_scheduler_type: polynomial
bf16: true
max_grad_norm: 1.0
warmup_steps: 20
weight_decay: 0.01

### eval
val_size: 0.05
per_device_eval_batch_size: 4
evaluation_strategy: steps
eval_steps: 20
save_total_limit: 1
save_only_model: true
