### model
model_name_or_path: OpenLeecher/llama_8b_lima_31

### method
stage: kto
pref_beta: 0.1
do_train: true
finetuning_type: full

### optim
flash_attn: fa2
enable_liger_kernel: true
optim: adamw_8bit

### ddp
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: open_webui_kto
dataset_dir: data
template: llama3
seed: 66
cutoff_len: 8192
preprocessing_num_workers: 16
use_fast_tokenizer: true

### output
output_dir: saves/full/Llama_Open_Webui_3.1_kto
logging_steps: 5
save_steps: 574
overwrite_output_dir: true
run_name: Llama_Open_Webui_3.1_kto

### hub
push_to_hub: true
hub_model_id: llama_8b_lima_31_kto
hub_strategy: end
hub_token: __HUB__TOKEN__PLACEHOLDER__

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 15
learning_rate: 0.0000015
num_train_epochs: 1.0
lr_scheduler_type: polynomial
bf16: true
max_grad_norm: 1.0
warmup_steps: 50
weight_decay: 0.003

### eval
val_size: 0.05
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 90
save_total_limit: 3
save_only_model: true
