### model
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
flash_attn: fa2
enable_liger_kernel: true
optim: adamw_8bit

### ddp
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: story_dataset
dataset_dir: data
template: llama3
seed: 66
cutoff_len: 3200
preprocessing_num_workers: 16
use_fast_tokenizer: true

### output
output_dir: saves/full/story_gen
logging_steps: 5
save_steps:  1000000
overwrite_output_dir: true
run_name: StoryGen

### hub
push_to_hub: true
hub_private_repo: true
hub_model_id: story_gen_10
hub_strategy: end
hub_token: __HUB__TOKEN__PLACEHOLDER__

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 4
learning_rate: 0.000006
num_train_epochs: 1.0
lr_scheduler_type: polynomial
bf16: true
max_grad_norm: 1.0
warmup_steps: 20
weight_decay: 0.1

### eval
val_size: 0.05
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 40
