### model
model_name_or_path: Qwen/Qwen2.5-1.5B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
flash_attn: fa2
enable_liger_kernel: true
optim: adamw_8bit

### ddp
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: story_rate_dataset
dataset_dir: data
template: qwen
seed: 66
cutoff_len: 6500
preprocessing_num_workers: 16
use_fast_tokenizer: true

### output
output_dir: saves/full/model
logging_steps: 5
save_steps: 1000000
overwrite_output_dir: true
run_name: StoryRate

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 0.00001
num_train_epochs: 1.0
lr_scheduler_type: polynomial
bf16: true
max_grad_norm: 1.0
warmup_steps: 20
weight_decay: 0.1

### eval
val_size: 0.05
per_device_eval_batch_size: 8
evaluation_strategy: steps
eval_steps: 40
