### model
model_name_or_path: /home/hidelord/text-generation-webui-snapshot-2024-04-14/models/story_technical_rate

### method
stage: kto
do_train: true
pref_beta: 0.075
finetuning_type: full
flash_attn: fa2
enable_liger_kernel: true
optim: adamw_8bit

### ddp
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: story_technical_rate_dataset_kto
dataset_dir: data
template: qwen
seed: 66
cutoff_len: 6000
preprocessing_num_workers: 16
use_fast_tokenizer: true

### output
output_dir: saves/full/model
logging_steps: 5
save_steps:  1000000
overwrite_output_dir: true
run_name: tech_rate_kto

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 6
learning_rate: 0.000001
num_train_epochs: 1.0
lr_scheduler_type: polynomial
bf16: true
max_grad_norm: 1.0
warmup_steps: 30
weight_decay: 0.05

### eval
val_size: 0.05
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100
save_total_limit: 1
save_only_model: true
