### model
model_name_or_path: unsloth/Llama-3.2-3B-Instruct

### method
stage: rm
do_train: true
finetuning_type: full
flash_attn: fa2
enable_liger_kernel: true
optim: adamw_8bit

### ddp
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: story_rate_dataset
dataset_dir: data
template: llama3
seed: 66
cutoff_len: 10000
preprocessing_num_workers: 32
use_fast_tokenizer: true

### output
output_dir: saves/full/story_rate_rm
logging_steps: 5
save_strategy: 'no'
overwrite_output_dir: true
run_name: StoryRateRm

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 32
learning_rate: 0.0000015
num_train_epochs: 1.0
lr_scheduler_type: polynomial
bf16: true
max_grad_norm: 1.0
warmup_steps: 35
weight_decay: 0.01

### eval
val_size: 0.05
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 100
save_total_limit: 1
save_only_model: true
save_safetensors: false
