### model
model_name_or_path: /home/hidelord/text-generation-webui-snapshot-2024-04-14/models/OpenLeecher_story_gen_1

### method
stage: sft
do_train: true
finetuning_type: lora
flash_attn: fa2
enable_liger_kernel: true
optim: adamw_8bit

### lora
lora_rank: 128
lora_alpha: 256
lora_dropout: 0.02
lora_target: all

### ddp
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: story_dataset
dataset_dir: data
template: llama3
seed: 66
cutoff_len: 4096
preprocessing_num_workers: 16
use_fast_tokenizer: true

### output
output_dir: saves/full/story_gen
logging_steps: 5
save_steps:  1000000
overwrite_output_dir: true
run_name: StoryGen

### hub
push_to_hub: false
hub_private_repo: true
hub_model_id: story_gen_1
hub_strategy: end
hub_token: __HUB__TOKEN__PLACEHOLDER__

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 1.0
lr_scheduler_type: polynomial
bf16: true
max_grad_norm: 1.0
warmup_steps: 25
weight_decay: 0.05

### eval
val_size: 0.05
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 40
