### model
model_name_or_path: /home/hidelord/text-generation-webui-snapshot-2024-04-14/models/story_technical_rate

### method
stage: kto
do_train: true
pref_beta: 0.075
finetuning_type: lora
flash_attn: fa2
enable_liger_kernel: true
optim: lion_8bit

### lora
quantization_bit: 8
lora_rank: 64
lora_alpha: 100
lora_dropout: 0.05
lora_target: all

### ddp
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: story_technical_rate_dataset_kto
dataset_dir: data
template: qwen
seed: 66
cutoff_len: 4000
preprocessing_num_workers: 16
use_fast_tokenizer: true

### output
output_dir: saves/lora/story_technical_rate_dataset_kto
logging_steps: 5
save_steps:  1000000
overwrite_output_dir: true
run_name: StoryTechnicalClass

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 7
learning_rate: 0.00001
num_train_epochs: 1.0
lr_scheduler_type: polynomial
bf16: true
max_grad_norm: 1.0
warmup_steps: 15
weight_decay: 0.05

### eval
val_size: 0.05
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 100
save_total_limit: 1
save_only_model: true
